[build]
  base = "apps/web"
  command = "npm install --production=false && npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[functions]
  directory = "../api"
  node_bundler = "esbuild"
  included_files = ["lib/prompts/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  command = "cd apps/web && npm run dev"
  port = 5173